name: Rust

on:
  push:
    branches: [ "main", "ShiftSwapStripe" ]
  pull_request:
    branches: [ "main", "ShiftSwapStripe" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Restore cache
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install TestU01
      run: |
        sudo apt-get update
        sudo apt-get install -y libtestu01-0-dev
    - name: Install nightly Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --lib --release
    - name: Save build and cache
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  run-unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TestU01
        run: |
          sudo apt-get update
          sudo apt-get install -y libtestu01-0-dev
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Non-BigCrush tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib --release -- --skip=test_big_crush
          toolchain: nightly
  bigcrush-basic:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TestU01
        run: |
          sudo apt-get update
          sudo apt-get install -y libtestu01-0-dev
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: BigCrush basic
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib prng::tests::test_big_crush_basic --release
          toolchain: nightly
  bigcrush-reversed-bits:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TestU01
        run: |
          sudo apt-get update
          sudo apt-get install -y libtestu01-0-dev
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: BigCrush with reversed bits
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib prng::tests::test_big_crush_reversed_bits --release
          toolchain: nightly
  bigcrush-upper-half:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TestU01
        run: |
          sudo apt-get update
          sudo apt-get install -y libtestu01-0-dev
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: BigCrush upper half
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib prng::tests::test_big_crush_upper_half --release
          toolchain: nightly
  bigcrush-lower-half:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: BigCrush lower half
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib prng::tests::test_big_crush_lower_half --release
          toolchain: nightly
  bigcrush-upper-half-reversed-bits:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TestU01
        run: |
          sudo apt-get update
          sudo apt-get install -y libtestu01-0-dev
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: BigCrush upper half
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib prng::tests::test_big_crush_upper_half_reversed_bits --release
          toolchain: nightly
  bigcrush-lower-half-reversed-bits:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TestU01
        run: |
          sudo apt-get update
          sudo apt-get install -y libtestu01-0-dev
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: BigCrush lower half
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib prng::tests::test_big_crush_lower_half_reversed_bits --release
          toolchain: nightly

