name: Rust

on:
  push:
    branches: [ "main", "ShiftSwapStripe" ]
  pull_request:
    branches: [ "main", "ShiftSwapStripe" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install TestU01
      run: |
        sudo apt-get update
        sudo apt-get install -y libtestu01-0-dev
    - name: Install nightly Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --lib --release
    - name: Output build for other jobs
      uses: actions/upload-artifact@v3
      with:
        name: build-target
        path: target
  run-unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build
      uses: actions/download-artifact@v3
      with:
        name: build-target
    - name: Non-BigCrush tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --lib --release -- --skip=test_big_crush
  bigcrush-basic:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-target
      - name: BigCrush basic
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib prng::tests::test_big_crush_basic --release
  bigcrush-reversed-bits:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-target
      - name: BigCrush with reversed bits
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib prng::tests::test_big_crush_reversed_bits --release
  bigcrush-upper-half:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-target
      - name: BigCrush upper half
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib prng::tests::test_big_crush_upper_half --release
  bigcrush-lower-half:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-target
      - name: BigCrush lower half
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib prng::tests::test_big_crush_lower_half --release
  bigcrush-upper-half-reversed-bits:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-target
      - name: BigCrush upper half
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib prng::tests::test_big_crush_upper_half_reversed_bits --release
  bigcrush-lower-half-reversed-bits:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-target
      - name: BigCrush lower half
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib prng::tests::test_big_crush_lower_half_reversed_bits --release

